function createfigure(X1, Y1, X2, Y2, Y3, Y4, Y5, Y6, Y7, Y8, Y9)
%CREATEFIGURE(X1, Y1, X2, Y2, Y3, Y4, Y5, Y6, Y7, Y8, Y9)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  Y3:  vector of y data
%  Y4:  vector of y data
%  Y5:  vector of y data
%  Y6:  vector of y data
%  Y7:  vector of y data
%  Y8:  vector of y data
%  Y9:  vector of y data

%  Auto-generated by MATLAB on 23-Sep-2018 19:00:26

% Create figure
figure1 = figure('Name','Orthogonalized shock to eps_a');

% Create subplot
subplot1 = subplot(3,3,1,'Parent',figure1);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[1 12]);
box(subplot1,'on');
hold(subplot1,'on');

% Create plot
plot(X1,Y1, 'Parent',subplot1,'LineWidth',1,'Color',[0 0 0]);

% Create plot
plot(X2,Y2,'Parent',subplot1,'Color',[1 0 0]);

% Create title
title('y_gap','Interpreter','none');

% Create subplot
subplot2 = subplot(3,3,2,'Parent',figure1);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[1 12]);
box(subplot2,'on');
hold(subplot2,'on');

% Create plot
plot(X1,Y3,'Parent',subplot2,'LineWidth',1,'Color',[0 0 0]);

% Create plot
plot(X2,Y2,'Parent',subplot2,'Color',[1 0 0]);

% Create title
title('pi_an','Interpreter','none');

% Create subplot
subplot3 = subplot(3,3,3,'Parent',figure1);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot3,[1 12]);
box(subplot3,'on');
hold(subplot3,'on');

% Create plot
plot(X1,Y4,'Parent',subplot3,'LineWidth',1,'Color',[0 0 0]);

% Create plot
plot(X2,Y2,'Parent',subplot3,'Color',[1 0 0]);

% Create title
title('y','Interpreter','none');

% Create subplot
subplot4 = subplot(3,3,4,'Parent',figure1);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot4,[1 12]);
box(subplot4,'on');
hold(subplot4,'on');

% Create plot
plot(X1,Y5,'Parent',subplot4,'LineWidth',1,'Color',[0 0 0]);

% Create plot
plot(X2,Y2,'Parent',subplot4,'Color',[1 0 0]);

% Create title
title('n','Interpreter','none');

% Create subplot
subplot5 = subplot(3,3,5,'Parent',figure1);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot5,[1 12]);
box(subplot5,'on');
hold(subplot5,'on');

% Create plot
plot(X1,Y6,'Parent',subplot5,'LineWidth',1,'Color',[0 0 0]);

% Create plot
plot(X2,Y2,'Parent',subplot5,'Color',[1 0 0]);

% Create title
title('i_an','Interpreter','none');

% Create subplot
subplot6 = subplot(3,3,6,'Parent',figure1);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot6,[1 12]);
box(subplot6,'on');
hold(subplot6,'on');

% Create plot
plot(X1,Y7,'Parent',subplot6,'LineWidth',1,'Color',[0 0 0]);

% Create plot
plot(X2,Y2,'Parent',subplot6,'Color',[1 0 0]);

% Create title
title('r_real_an','Interpreter','none');

% Create subplot
subplot7 = subplot(3,3,7,'Parent',figure1);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot7,[1 12]);
box(subplot7,'on');
hold(subplot7,'on');

% Create plot
plot(X1,Y8,'Parent',subplot7,'LineWidth',1,'Color',[0 0 0]);

% Create plot
plot(X2,Y2,'Parent',subplot7,'Color',[1 0 0]);

% Create title
title('m_cresc_an','Interpreter','none');

% Create subplot
subplot8 = subplot(3,3,8,'Parent',figure1);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot8,[1 12]);
box(subplot8,'on');
hold(subplot8,'on');

% Create plot
plot(X1,Y9,'Parent',subplot8,'LineWidth',1,'Color',[0 0 0]);

% Create plot
plot(X2,Y2,'Parent',subplot8,'Color',[1 0 0]);

% Create title
title('a','Interpreter','none');

